### ISSUE TITLE
How to define an aggregate function?

### ISSUE THREAD

**Issue by Horusiath** [zombodb/pgx#102]
Hi. Before I begin - thanks for this great project!

I'm trying to build an aggregate function for my custom data type as described in [Postgres documentation](https://www.postgresql.org/docs/10/xaggr.html). However I couldn't find a programmatic way of declaring such function using pgx API. It doesn't seem to be possible from Rust level - only from custom sql load scripts, or did I miss something?

**Comment by eeeebbbbrrrr** [comment]
Hey!  I haven't sat down to implement aggregate functions myself, but it should be doable.  You'd define the various init/collect/finalize functions you need as standard `[pg_extern]` functions, and then use the `extension_sql!` macro to handwrite the `CREATE AGGREGATE` statement.

Also, it's undocumented right now, but pgx has `pgx::pg_func_extra()` which lets you setup the "fn_extra" pointer.  You do need the `pg_sys::FunctionCallInfo` pointer, but that's easy to get -- just declare that as your **last** argument of any `#[pg_extern]` function.

I'd like to see better organization around this as time goes one.  I think pgx can make the story around custom aggregate functions very compelling.

**Comment by laysakura** [comment]
Here shows an example on how to create `MYAVG` aggregate:
https://github.com/laysakura/pgx-kungfu/blob/ebc658b819732fb1ea581a5cd4aecaad474bfbc8/my_extension/src/lib.rs

I just followed the above advise:

> You'd define the various init/collect/finalize functions you need as standard [pg_extern] functions, and then use the extension_sql! macro to handwrite the CREATE AGGREGATE statement.

**Comment by Hoverbear** [comment]
It seems this is possible and we should create an example demonstrating this for PGX proper!
