### ISSUE TITLE
Please add cargo-pgx to nixpkgs

### ISSUE THREAD

**Issue by W1M0R** [zombodb/pgx#104]
I have tried to build a Nix derivation for cargo-pgx, that would build cargo-pgx and install it into my nix-shell, but my knowledge of nix is unfortunately lacking. 

It would be great if cargo-pgx can be added to the Nix Package Registry. This would involve a contribution to https://github.com/NixOS/nixpkgs.  Here are all the other cargo subcommands that can be found in the Nix Package Registry: https://search.nixos.org/packages?channel=20.09&from=0&size=50&sort=relevance&query=cargo

Here is the (very simple) Nix derivation for the `cargo web` subcommand: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/cargo-web/default.nix

Here was my (failed) attempt at packaging cargo-pgx:

```nix
# https://github.com/NixOS/nixpkgs/issues/89563
# https://github.com/NixOS/nixpkgs/issues/32720
# https://github.com/NixOS/nixpkgs/issues/37945
# https://github.com/zombodb/pgx
# https://github.com/zombodb/pgx/tree/master/cargo-pgx
# https://eipi.xyz/blog/packaging-a-rust-project-for-nix/
# https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md
# https://crates.io/crates/pgx
# https://discourse.nixos.org/t/how-to-install-openssl-to-compile-against/1249/2
# https://nixos.org/manual/nixpkgs/stable/#chap-multiple-output
# https://github.com/zombodb/pgx/issues/96
# https://nixos.org/manual/nixpkgs/stable/#chap-stdenv
# https://github.com/NixOS/nixpkgs/issues/31172
# https://github.com/NixOS/nixpkgs/issues/15495
# https://github.com/zombodb/pgx/blob/master/cargo-pgx/README.md
# https://github.com/kolloch/crate2nix/issues/148#issuecomment-699630254
# https://github.com/NixOS/nixpkgs/issues/15003
# https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands
# Adding ~/.cargo/bin: to your PATH might help.

{ rustPlatform, buildRustPackage, fetchFromGitHub, lib, openssl, pkg-config, mkDerivation }:

buildRustPackage rec {
    pname = "pgx";
    version = "0.1.19";

    src = fetchFromGitHub {
        owner = "zombodb";
        repo = pname;
        rev = "v${version}";
        # sha256 = "0000000000000000000000000000000000000000000000000000";
        # sha256 = lib.fakeSha256;
        sha256 = "0a5cifln9dg3wdlpvkdy3lkccdwdfn51a360hnqrwv27lpalw1ap";
    };

    # cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    # cargoSha256 = lib.fakeSha256;
    cargoSha256 = "18501z19n3ca70jg5l62bn1rki41f2gdlyji5ygbv7fja7p7dsrv";

    # cargoRoot = "source";

    # sourceRoot = ".";
    # sourceRoot = "source/cargo-pgx";
    # cargoPatches = [
    #     ./add-Cargo.lock.patch
    # ];

    nativeBuildInputs = [ pkg-config ];

    buildInputs = [ openssl ];

    # https://github.com/zombodb/pgx/blob/master/cargo-pgx/Cargo.toml
    # cargoDepsName = "cargo-pgx";
    # https://github.com/zombodb/pgx/blob/master/Cargo.toml
    cargoDepsName = "pgx-parent";

    meta = with lib; {
        description = "Build Postgres Extensions with Rust!";
        homepage = "https://github.com/zombodb/pgx";
        license = licenses.mit;
        maintainers = [ maintainers.eeeebbbbrrrr ];
    };
}

```

Here is the error that I get when this Nix derivation is executed:

```shell
error: failed to run custom build command for `pgx-pg-sys v0.1.19 (/build/source/pgx-pg-sys)`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/pgx-pg-sys-1a789ec37c83b22c/build-script-build` (exit code: 1)
  --- stderr
  manifest_dir=/build/source/pgx-pg-sys
  shim_dir=/build/source/pgx-pg-sys/cshim
  Error: Custom { kind: NotFound, error: "/homeless-shelter/.pgx/config.toml not found.  Have you run `cargo pgx init` yet?" }
warning: build failed, waiting for other jobs to finish...
error: build failed
builder for '/nix/store/aq4y3jmvzy5jrakwv5lymz4a37hkhlnl-pgx-0.1.19.drv' failed with exit code 101
error: build of '/nix/store/aq4y3jmvzy5jrakwv5lymz4a37hkhlnl-pgx-0.1.19.drv' failed
```

I'm not sure whether the project layout would have to change, or whether a Cargo.lock would have to be added for the cargo-pgx project, or whether the pgx-pg-sys project can be excluded from the general build. With my Nix derivation, all the Rust projects in this repository is built. Ideally, I would like to have only cargo-pgx built.

**Comment by eeeebbbbrrrr** [comment]
I don't know anything about Nix so I have no idea how to help, but a couple of points.

> cargoDepsName = "pgx-parent";

`pgx-parent` isn't a thing you should need as a dependency for `cargo-pgx`.  It's not a thing you need as a dependency for anything based on `pgx` either.

> NotFound, error: "/homeless-shelter/.pgx/config.toml not found.  Have you run `cargo pgx init` yet?"

That's probably the problem here.  After getting `cargo-pgx` installed, you need to run `cargo pgx init` at least once.

> Here is the error that I get when this Nix derivation is executed:

I'm not sure what this means or what was actually executed?  But the error you got would be from trying to build a rust crate with a dependency on either the `pgx` or `pgx-pg-sys` crates, not `cargo-pgx` itself.

**Comment by W1M0R** [comment]
Thanks for the feedback @eeeebbbbrrrr, I appreciate it. If I manage to figure out a Nix expression that works, I'll attach it to this issue.

**Comment by Hoverbear** [comment]
Hey @W1M0R , we have a Nix flake for PGX now (and a cargo-pgx package), can you use this? #124 

Because that *should* resolve this issue for you, I'll close it. Let me know if it doesn't work for you!

**Comment by W1M0R** [comment]
Thanks @Hoverbear, I'll give it a go!

**Comment by wpcarro** [comment]
Any reason to *not* publish this to nixpkgs? I'm not using flakes e.g.

**Comment by Hoverbear** [comment]
@wpcarro Sometimes the official Nixpkgs Rust version, and our MSRV differ. We also use Naersk, which is not part of Nixpkgs. Even if your system only *supports* flakes (but you don't use them otherwise), you can get the package with `(builtins.getFlake "github:tcdi/pgx").outputs.packages.x86_64-linux.cargo-pgx`

**Comment by wpcarro** [comment]
> Even if your system only supports flakes (but you don't use them otherwise), you can get the package with (builtins.getFlake "github:tcdi/pgx").outputs.packages.x86_64-linux.cargo-pgx

TIL `builtins.getFlake`. Ty for the thoughtful, patient response :)

**Comment by Hoverbear** [comment]
Glad it worked. :) Any improvements to the nix stuff is welcome by the way! We don't use it heavily.
