### ISSUE TITLE
Please allow cargo pgx package to accept postgres installed during init

### ISSUE THREAD

**Issue by W1M0R** [zombodb/pgx#105]
It would be great if it were possible to use one of the downloaded postgres versions to create an installation package, e.g. `cargo pgx package pg12`. This would find the pg_config based on the cargo-pgx config.toml file.

**Comment by eeeebbbbrrrr** [comment]
The problem with this approach is that you really need a packaged extension (one that you're likely going to redistribute) to be build using the same set of headers that were generated for the target Postgres package.  

`cargo-pgx` enables various debugging options and compiles without optimizations for the Postgres versions it manages -- none of which is ideal for a release package.

**Comment by W1M0R** [comment]
Thanks for the insight. I decided not to install a version of postgres in my development environment, and instead configured my PATH to point to the pg_config of one of the postgres versions installed by cargo-pgx. Does that mean the resulting dynamic library for the extension, would have been built with debugging symbols, etc, because it used the debugging headers of the cargo-pgx postgres installation? Do you think if I distribute this packaged extension, that it would not work (I plan on using it with a postgres installation in a Docker image), or that it would perform sub-optimally?

**Comment by eeeebbbbrrrr** [comment]
One thing I didn't mention is that `cargo pgx package` (and `install` for that matter) get the paths to where Postgres expects the extension .sql and .so files to be installed.

As such, f you use the Postgres managed by pgx to build a release package, `cargo pgx` will use those paths, which are compiled into `pg_config`.  That almost certainly not what you'd want.

Take a look at what I'm doing with @zombodb (https://github.com/zombodb/zombodb/tree/master/docker-build-system).  It might be a bit over-engineered, but it uses docker to build release packages for ZDB against the various known-to-be-good Linux distro packages.  Maybe there's some inspiration there for you.

I've thought about migrating all that into cargo-pgx itself (or a secondary tool or something), but am not 100% sure it's the right solution.

You're not the first one to mention the general issue of building release packages for pgx-based extensions, so I definitely want to solve the problem -- it's just not clear if there's a general solution for everyone.

**Comment by W1M0R** [comment]
I managed to successfully `cargo pgx package` my extension within an Ubuntu `nix-shell` environment using the postgres downloaded by `cargo pgx init`, and to copy the resulting extension `.so`, `.sql` and `.control` files from the `CARGO_TARGET_DIRECTORY` into a Debian-based postgres Docker Image. So I ended up not needing to use `cargo pgx package` or `cargo pgx install` within my postgres Docker image.

Within the Docker container, I did a `readelf` and `ldd` to verify the extension `.so` file dependencies. Then I ran psql inside the Docker container and performed a `CREATE EXTENSION` and successfully called my extension functions.

Here are the details if they are helpful to anyone:

```bash
readelf -d /usr/lib/postgresql/12/lib/sdlpgx.so

Dynamic section at offset 0x3db58 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/s8gc58w45rhs4lyd8z4bslws0bxlwsvj-nix-shell/lib64:/nix/store/s8gc58w45rhs4lyd8z4bslws0bxlwsvj-nix-shell/lib:/nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib:/nix/store/z5l2fm9byiz5yr82iznkv2rynr85ajnv-gcc-10.2.0-lib/lib]
 0x000000000000000c (INIT)               0x5000
 0x000000000000000d (FINI)               0x32f70
 0x0000000000000019 (INIT_ARRAY)         0x3cde0
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x3cdf0
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x238
 0x000000006ffffef5 (GNU_HASH)           0x590
 0x0000000000000005 (STRTAB)             0xd50
 0x0000000000000006 (SYMTAB)             0x5e8
 0x000000000000000a (STRSZ)              1526 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x3ed88
 0x0000000000000002 (PLTRELSZ)           432 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x3e88
 0x0000000000000007 (RELA)               0x14b8
 0x0000000000000008 (RELASZ)             10704 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x13e8
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x1346
 0x000000006ffffff9 (RELACOUNT)          390
 0x0000000000000000 (NULL)               0x0
```

```bash
ldd /usr/lib/postgresql/12/lib/sdlpgx.so
        linux-vdso.so.1 (0x00007ffe087ec000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fea93234000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fea93213000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fea93052000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fea93294000)
```

```
psql=# create extension sdlpgx;
CREATE EXTENSION
psql=# select sdlpgx_hello();
 sdlpgx_hello
---------------
 Hello, sdlpgx
(1 row)

psql=#
```

```
{ project ? import ../nix { }
}:

project.pkgs_next.mkShell rec {

  glibcLocales = project.pkgs_next.glibcLocales;
  # https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/rust/bindgen/default.nix
  libclang = project.pkgs_next.llvmPackages.libclang.lib;

  buildInputs = builtins.attrValues {

    # dev tools
    inherit (project.pkgs_next) exa;
    inherit (project.pkgs_next) gnumake;
    inherit (project.pkgs_next) which;
    inherit (project.pkgs_next) glances;

    # We need a postgres with a writeable environment, to install the extension
    # and iterate during development, so we have to let cargo pgx manage the
    # installation.
    # inherit (project.pkgs_next) postgresql_12;
    # inherit (project.pkgs_next) pkg-config;

    # cargo pgx dependencies
    # https://github.com/zombodb/pgx#system-requirements
    # https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code
    inherit (project.pkgs_next) cargo;
    inherit (project.pkgs_next) rustc;
    inherit (project.pkgs_next) rustfmt;
    inherit libclang;
    inherit (project.pkgs_next) clang;
    inherit (project.pkgs_next) git;
    inherit (project.pkgs_next) openssl;
    inherit glibcLocales;
    inherit (project.pkgs_next) bison;
    inherit (project.pkgs_next) flex;
    inherit (project.pkgs_next) readline;
    inherit (project.pkgs_next) zlib;

    # unforunately cargo-pgx can not yet be installed
    # TODO: https://github.com/zombodb/pgx/issues/104
    # inherit (project) cargo-pgx;
  };
  shellHook = ''
    # The default TMPDIR available to nix uses the memory-based tmpfs, which
    # does not provide enough storage for the rust compiler.
    export TMPDIR=/tmp

    # The cargo-pgx installed postgres does not want to start if these values
    # are not set.
    export LOCALE_ARCHIVE_2_27="${glibcLocales}/lib/locale/locale-archive"
    export LIBCLANG_PATH="${libclang}/lib"

    # The default PGX_HOME is set to ~/.pgx/. We are setting it explicitly.
    # https://github.com/zombodb/pgx/tree/master/cargo-pgx#environment-variables
    export PGX_HOME=~/.pgx

    # The default CARGO_TARGET_DIR places the cargo compiler output in
    # $PWD/target. This causes build performance issues because the parent
    # folder is shared with VirtualBox and has trouble with hard/soft links.
    # Here we choose a different path so that it lives outside any VirtualBox
    # shared folders. Ideally, the Cargo.lock dependencies should be vendored.
    # https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads
    export CARGO_TARGET_DIR=~/.cargo-targets/sdlpgx

    # Cargo's local cache.
    # https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads
    export CARGO_HOME=~/.cargo

    # The path to the local postgres installation managed by cargo-pgx.
    # NOTE: Unfortunately cargo-pgx only accepts a major version number, via the
    # --pg12 flag. So this build is not reproducible and will fail if a new
    # checkout is performed and new minor versions of postgres 12 become,
    # available, let's say 12.7.
    export PGX_PG12=$PGX_HOME/12.6
    export PGX_PG12_HOME=$PGX_PG12/pgx-install
    export PATH=$PATH:$PGX_PG12_HOME/bin
  '';
}

```

Perhaps what I am looking for from `pgx`, is that the `package` command should just place the generated `.so` file, `.control` file and `.sql file`, in a known directory specified by me, and that it should use whatever postgres was configured with `init`, even if it is the postgres managed by `pgx`. Then my own build tools can copy and install the files wherever they need to be. However, as shown above, I can work with the current way that `pgx` is doing it, by manually setting my PATH to use the downloaded pg_config, and my copying the release from the cargo target directory. It would just simplify the distribution process if `pgx` itself could accept packaging options for this kind of workflow.

**Comment by Hoverbear** [comment]
Hey @W1M0R ! You can do this now with 

```bash
cargo pgx init \
    --pg10 ${postgresql_10}/bin/pg_config \
    --pg11 ${postgresql_11}/bin/pg_config \
    --pg12 ${postgresql_12}/bin/pg_config \
    --pg13 ${postgresql_13}/bin/pg_config
```

As you can see in https://github.com/zombodb/pgx/blob/b57522ef29a4ac8939829019ca06b7e2aa4bbfea/cargo-pgx/default.nix#L19-L25.

However please note you need to make sure these directories are writable (which, in the case of nix store pathes, they are not), so you'd want to copy them into a writable location or something.

Because this feature appears to exist, and you appear to have solved it yourself anyways, I'll close this! Feel free to reopen it.

**Comment by W1M0R** [comment]
Thanks!
