### ISSUE TITLE
Rework cargo-pgx with different abilities

### ISSUE THREAD

**Issue by zombodb** [zombodb/pgx#14]
- [x] `build.rs` no longer downloads/compiles postgres.  It'll instead be limited to generating the "bindgen" bindings for each version and compiling pgx's "cshim" static library (this'll be difficult to resolve for Windows users, I think)
 - [x] `cargo pgx init` comes to life and it does the dowload/compile Postgres versions dance (in parallel) into `~/.pgx/`, or it can use any/all Postgres versions you might already have installed on your computer, specified via args to `cargo pgx init`.  Paths to each version's `pg_config` will be saved in `~/.pgx/config.toml`.
 - [x] `cargo pgx install` stays, and continues to simply compile/install the extension to the Postgres instance specified by whatever `pg_config` binary is currently on the `$PATH`
 - [x] `cargo pgx start PG_VER` comes to life to start a pg instance, specific to `pgx`
 - [x] `cargo pgx stop PG_VER` comes to life to stop a pg instance, specific to `pgx` 
 - [x] `cargo pgx status [pg_ver]` comes to life to see what's up with a pg instance, specific to `pgx` 
 - [x] `cargo pgx run PG_VER [dbname]` comes to life and it compiles/installs the extension to the PG instance described in `~/.pgx/config.toml` and starts it (if not already running) and immediately pops you into `psql` connected to the specified database (if unspecified, the dbname will be the extension name, creating it if necessary).
 - [x] `caro pgx test [pg_ver]` stays, but will spin up a temporary Postgres instance using what `~/.pgx/config.toml` points to
 - [x] `cargo pgx package` builds (at least) a directory structure in `target/` that can be manually (for now) turned into a tarball/deb/rpm

In the case of using Postgres instances already installed on your computer (likely through your OS' package manager) you'll need write access to the directories from `pg_config --pkglibdir` and `pg_config --sharedir`.  You'll be on your own to sort that out.

I think maybe the typical workflow here is that you'll have one primary version of Postgres installed (via apt/dnf/brew/whatever), and then `cargo pgx init` will manage the other two.  So for example, you might first invoke `cargo pgx init` like so:

```shell_script
$ cargo pgx init --pg12 /usr/bin/pg_config
```

At this point, `cargo pgx init` will only download/compile/install PG10 and PG11.

There'll be system requirements on (at least)

 - a C compiler toolchain (gcc, clang/llvm)
 - libreadline-dev [ubuntu] (for compiling Postgres with that support)
 - zlib1g-dev [ubuntu] (for compiling Postgres with that supprt)

Additionally, the Postgres versions that `cargo pgx init` does compile itself will have `'--enable-debug' '--enable-cassert'` turned on so that in the case of core dumps, they can be debugged with gdb/lldb.

**Comment by zombodb** [comment]
Notes to self:

 - document the `PGX_BUILD_FLAGS` envar for `cargo pgx install/test` (and likely package too)
 - invent a `PGX_HOME` envvar for using a directory other than `~/.pgx/`

**Comment by diegopy** [comment]
Awesome work! I was fighting with pgx install but this is really what's needed to make the workflow better.
Have you guys considered a docker based workflow? I used dockerized postgres instances for development and works like a charm.I could help adding the support on pgx if that's something of interest.

**Comment by eeeebbbbrrrr** [comment]
Hey @diegopy!  Thanks for this comment.  We're working really hard to make `cargo pgx` better.  We kinda missed the boat on this initial release.  But we ain't afraid to admit it.

I just wrapped up a 1h 45m twitch stream showing off the work we've done on this issue (https://www.twitch.tv/videos/682684142).  When you get bored, watch it (FF through the first 10mins or so).

Regarding Docker ... you're not the first person to suggest that.  Once this issue is resolved, I think it might make sense to talk about it.

At some point, it seems to me that if you choose to use `pgx`, you've decided to become a PG developer.  And with that comes some stress and responsibility.  That said, if we can make all that disappear, I'm down!

**Comment by eeeebbbbrrrr** [comment]
Okay, I think I'm done with all of this.

Soon as one of these stupid GitHub Action test workflows that take way too long finishes with success, I'm going to merge.  And start the process to publish a new release.

**Comment by eeeebbbbrrrr** [comment]
released to crates.io
