### ISSUE TITLE
Cursor style functionality

### ISSUE THREAD

**Issue by Jon-Murray** [zombodb/pgx#140]
Heya, i've been playing with the library for a few weeks now and it has been spot on in every way possible. The only thing i've been wondering about it either the limiting of rows returned in SRFs, or the ability to add in a cursor-like function/ality.

For example:

	`
	  #[pg_extern]
	  fn jontest() -> impl std::iter::Iterator<Item = i32>
	  {
		  pgx::log::elog(INFO, "called jontest initial");

		  return jontest { curval: 1 };
	  }

		impl Iterator for jontest
	  {
		type Item = i32;

		fn next(&mut self) -> Option<Self::Item>
		{
			pgx::log::elog(INFO, format!("next called cur is {}", self.curval).as_str());

			self.curval += 1;

			if self.curval < 200
			{
				return Some(self.curval);
			}

			return None;
		}
	  }
	`

currently this will hit the iterator 200 times (ie, you'd see 200 log messages) even if you do something like:

select * from jontest() limit 10

The situation I have is that i'd have an external service which would be accessed by http in batches each time the iterator is called (ie. in the above, curval % 10 == 0 ? get another batch of 10 things) which is costly. I'm not a postgres noob, but definitely not an expert, but the only thing i've heard of which can mimic this functionality is a cursor type. So i guess there are three questions: 

- firstly, am i doing something wrong with this? 
- is there any way to achieve this functionality without a cursor type (i appreciate this isn't stackoverflow and i'm sorry to ask but it hopefully will help someone else in the future if anyone knows)
- lastly, do you think at some point a cursor style interface would be possible?

Thanks once again for the great lib

**Comment by eeeebbbbrrrr** [comment]
I don't think set-returning functions are allowed to terminate early.  One reason is that there's a "finish" step in the API to cleanup resources when the function is complete.

Another would just be SQL itself.  Lets say your sql was instead `SELECT * FROM jontest() ORDER BY random() LIMIT 10;`  What would you expect it to do in that case?

I think the best you can do is add another argument to your function for the limit, and not rely on the postgres LIMIT clause.
