### ISSUE TITLE
Feature request: TimestampWithTimeZone conversion to std::time::SystemTime

### ISSUE THREAD

**Issue by W1M0R** [zombodb/pgx#153]
According to https://github.com/zombodb/pgx/blob/e12d8e883dc9e882214db0e1393a1e0b9c43d2db/pgx/src/datum/time_stamp_with_timezone.rs#L10

pgx::TimestampWithTimeZone is related to time::OffsetDateTime of the crates.io time package. I am looking for a way to convert pgx::TimestampWithTimeZone to std::time::SystemTime, and could achieve it as follows:

```rust
#[pg_extern]
fn my_func(my_time: TimestampWithTimeZone) {
    let my_time_base: time::OffsetDateTime = *my_time;
    let my_time_sys = SystemTime::from(my_time_base); // SystemTime::from is implemented for time::OffsetDateTime
    ...
}
```

I also needed to add `time = "0.2.26"` to my `Cargo.toml` file.

Although my current solution seems to work (I am still going to test it), it would be better if I could decouple my solution from pgx implementation details (e.g. TimestampWithTimeZone may choose to use a different time library in the future, perhaps chrono, etc.). I also don't really want to have to synchronize my Cargo.toml file's `time` package with the one used by pgx.

I get the following error if I do `SystemTime::from(my_time)` instead: 

```
 ^^^^^^^^^^^^^^^^ the trait `std::convert::From<pgx::TimestampWithTimeZone>` is not implemented for `SystemTime`
```

Please consider providing an implementation for the trait.

Apologies for not providing a better description, my understanding of Rust is still very basic.

Some references:

1. https://github.com/time-rs/time/blob/b6c5128bff6fbf25a249eb09edf6d7521bdc6029/src/offset_date_time.rs#L1029
2. https://github.com/time-rs/time/blob/b6c5128bff6fbf25a249eb09edf6d7521bdc6029/src/offset_date_time.rs#L1040
3. https://github.com/time-rs/time/commit/a51e23b4b9611b3ee885c489b6310f48a82e04f5

**Comment by eeeebbbbrrrr** [comment]
Let us consider and otherwise look into this.  Dealing with times and especially time zones is harder than granite. 

We’ll circle back here soon.

**Comment by W1M0R** [comment]
Thanks for the consideration. I agree. That's why I am also a little bit cautious about making assumptions about the underlying implementation.

**Comment by eeeebbbbrrrr** [comment]
I gotta tell ya. Despite all the complexities in pgx, of which there are many, dealing with mapping Postgres’ date/time types to Rust was the absolute most difficult.  

And I would expect that we got it wrong.  

Any advice you can share would be appreciated!

**Comment by W1M0R** [comment]
Thanks for the headsup! I can imagine. I skimmed through pgx's date/time serialization code and the level of thought put into it is impressive. But if I do think of anything positive to contribute, then I'll let you know.

**Comment by eeeebbbbrrrr** [comment]
Even if it’s less “…” and more “this is the answer I expect”, we’ll take it.

**Comment by W1M0R** [comment]
The following code fails in my project, but something to that effect should work:

```rust
use core::convert::From;
use std::time::SystemTime;
use time;
use pgx;
impl From<pgx::TimestampWithTimeZone> for SystemTime {
    fn from(t: pgx::TimestampWithTimeZone) -> Self {
        SystemTime::from(t.0) // using Rust Tuple Struct syntax
    }
}
```

The error I get is:
```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/lib.rs:31:1
   |
31 | impl From<pgx::TimestampWithTimeZone> for SystemTime {
   | ^^^^^--------------------------------^^^^^----------
   | |    |                                    |
   | |    |                                    `SystemTime` is not defined in the current crate
   | |    `pgx::TimestampWithTimeZone` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead

```

**Comment by Hoverbear** [comment]
Hi @W1M0R, unfortunately `SystemTime` and `TimestampWithTimeZone` are not equivalent. :(

From reading https://www.postgresql.org/docs/13/datatype-datetime.html this type can represent dates far outside the normal range of `SystemTime` (which is generally a non-monotonic UNIX clock).

You can turn your `TimestampWithTimeZone` into a `std::time::Duration` since the `std::time::UNIX_EPOCH` with:

```rust
let since_epoch = Duration::from_nanos(my_timestamp.unix_timestamp_nanos());
```

Then you could do something like:

```rust
std::time::UNIX_EPOCH.checked_add(since_epoch).unwrap("Can't represent with SystemTime!");
```
