### ISSUE TITLE
pgx dump-schema should be able to write to STDOUT

### ISSUE THREAD

**Issue by timClicks** [zombodb/pgx#154]
At the moment, `pgx dump-schema` requires a directory as an option. In my opinion, it should write to STDOUT if no directory is specified.

**Comment by Hoverbear** [comment]
Noting #165 removes `dump-schema` and permits `cargo pgx schema -o /dev/stdout | bat -l sql` etc.

**Comment by Hoverbear** [comment]
This feature was merged into `develop`.
