### ISSUE TITLE
pgx init downloads pg versions it already has 

### ISSUE THREAD

**Issue by timClicks** [zombodb/pgx#156]
If you run `pgx init` for a second time, `pgx` will download Postgres versions that you already have.

```console
$ cargo pgx --version
cargo-pgx 0.1.21

$ cargo pgx init
  Discovered Postgres v13.3, v12.7, v11.12, v10.17
  Downloading Postgres v10.17 from https://ftp.postgresql.org/pub/source/v10.17/postgresql-10.17.tar.bz2
  Downloading Postgres v12.7 from https://ftp.postgresql.org/pub/source/v12.7/postgresql-12.7.tar.bz2
  Downloading Postgres v13.3 from https://ftp.postgresql.org/pub/source/v13.3/postgresql-13.3.tar.bz2
  Downloading Postgres v11.12 from https://ftp.postgresql.org/pub/source/v11.12/postgresql-11.12.tar.bz2
     Removing /home/tim/.pgx/10.17
    Untarring Postgres v10.17 to /home/tim/.pgx/10.17
  Configuring Postgres v10.17
    Compiling Postgres v10.17
...
```

**Comment by eeeebbbbrrrr** [comment]
What would you rather it do?

This is by design as it’s a way to get back to known-good-pg-installs without also losing your existing data directories.

**Comment by timClicks** [comment]
Oh, I would expect it to skip any exact versions that it's already discovered.

**Comment by Hoverbear** [comment]
@timClicks so you would expect it to store the download archives of the postgreSQL versions somewhere?

**Comment by timClicks** [comment]
That's probably not necessary. Couldn't you just check `~/.pgx` at the discovery time for versions that are already managed by pgx?

**Comment by Hoverbear** [comment]
That version might have been corrupted or damaged, since all versions are currently installed at once, I'm not sure what benefit this feature would provide. Maybe this would be more appropriate if we allowed users to only download/init specific versions?

**Comment by timClicks** [comment]
Actually, that's a good point. If someone is running `pgx init` a second time, then they probably broke something. In my case though, I just pushed up too many times in my shell and hit <kbd>Enter</kbd> too quickly.

**Comment by Hoverbear** [comment]
I think one thing we could do is prepare the new `.cargo` in a temporary directory, then swap it in once it's known good, so a user cancelling won't break an existing install.
