### ISSUE TITLE
Document `#[pg_extern(immutable)]`

### ISSUE THREAD

**Issue by timClicks** [zombodb/pgx#160]
`pgx` supports the ability to create so called [immutable functions][] via `#[pg_extern(immutable)]`. We should document this feature.

[immutable functions]: https://www.postgresql.org/docs/current/xfunc-volatility.html

**Comment by timClicks** [comment]
> An IMMUTABLE function cannot modify the database and is guaranteed to return the same results given the same arguments forever. This category allows the optimizer to pre-evaluate the function when a query calls it with constant arguments. For example, a query like SELECT ... WHERE x = 2 + 2 can be simplified on sight to SELECT ... WHERE x = 4, because the function underlying the integer addition operator is marked IMMUTABLE.

**Comment by Hoverbear** [comment]
We do this on `develop` now: 

https://github.com/zombodb/pgx/blob/235e8ff4f2eb69fd848f6adcaf839cb545386585/pgx-macros/src/lib.rs#L387-L403
