### ISSUE TITLE
pgx-pg-sys compile issues on FreeBSD

### ISSUE THREAD

**Issue by ak-coram** [zombodb/pgx#179]
I'm trying to compile the default extension (created via `cargo pgx new`) on FreeBSD 13.0, but the build fails with these errors:

[out.txt](https://github.com/zombodb/pgx/files/7062083/out.txt)

I was hopeful because compiling `pgx` and `pgx init` all worked fine. These seem like low-level errors, but I'm not sure about the cause. Any ideas? Thanks!

**Comment by eeeebbbbrrrr** [comment]
released: https://github.com/zombodb/pgx/releases/tag/v0.1.22
