### ISSUE TITLE
tokio-timer raising 'elapsed=44; when=43' error

### ISSUE THREAD

**Issue by marklit** [zombodb/pgx#182]
I'm running cargo-pgx 0.1.22 and rustc 1.54.0 (a178d0322 2021-07-26).

I've built the following extension using pgx and I'm running it on PostgreSQL 13.4 on Ubuntu 20.04 LTS with 16 GB of RAM. The table it's running on has 92 GB of data in PostgreSQL's internal format and approx 1.27B rows.

```rust
use pgx::*;
use tldextract::{TldExtractor, TldOption};

pg_module_magic!();

#[pg_extern]
fn get_sld(hostname: &str) -> String {
    let https_domain = format!("https://{}", &hostname);

    let options = TldOption {
       cache_path:      Some(".tld_cache".to_string()),
       private_domains: false,
       update_local:    false,
       naive_mode:      false,
    };
    let tld_ex = TldExtractor::new(options);

    if let Ok(domain_parts) = tld_ex.extract(&https_domain) {
        domain_parts.domain.unwrap()
    } else {
        error!("Unable to extract SLD from {}", hostname)
    }
}
```

The ``Cargo.toml`` file is as it was generated with the addition of ``tldextract = "0.5.1"`` as a dependency.

If I run the following on up to 800 rows it'll return without issue.

```sql
SELECT ipv4, get_sld(hostname)
FROM rdns
LIMIT 800;
```

But from around 800 rows upward I'm getting the following error message:

```
ERROR:  elapsed=44; when=43
CONTEXT:  /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/wheel/mod.rs:220:9
```

There have been a few variations of the above with each test I've tried. ``ERROR:  elapsed=53; when=52`` is another such example.

Looking at ``/home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/wheel/mod.rs`` I can see its failing inside of a ``set_elapsed`` function.

```rust
   219	    fn set_elapsed(&mut self, when: u64) {
   220	        assert!(
   221	            self.elapsed <= when,
   222	            "elapsed={:?}; when={:?}",
   223	            self.elapsed,
   224	            when
   225	        );
   226	
   227	        if when > self.elapsed {
   228	            self.elapsed = when;
   229	        }
   230	    }
```

I tried syncing the clock on my machine but the above error persists.

```bash
$ sudo ntpdate -s time.nist.gov
```

Any idea how I can fix the above?

**Comment by eeeebbbbrrrr** [comment]
You might try making this:

```rust
let options = TldOption {
       cache_path:      Some(".tld_cache".to_string()),
       private_domains: false,
       update_local:    false,
       naive_mode:      false,
    };
    let tld_ex = TldExtractor::new(options);
```

into constants, or perhaps a `lazy_static!` if `TldExtractor::new()` isn't const-able.

I've never used this stuff, or (afaik) anything that relies on tokio, so it's hard for me to say.  I also suspect this will help with the other issue (#183).

**Comment by marklit** [comment]
I ran ``cargo update`` and the tokio issue isn't manifesting itself anymore. It could be somewhere between tokio v1.10.1 and v1.11.0 the underlying issue was patched.

```bash
$ cargo update
```

```
Updating crates.io index
Updating cc v1.0.69 -> v1.0.70
Updating proc-macro2 v1.0.28 -> v1.0.29
Updating siphasher v0.3.6 -> v0.3.7
Updating tokio v1.10.1 -> v1.11.0
Updating typenum v1.13.0 -> v1.14.0
```

**Comment by marklit** [comment]
@jonititan No, I was never able to get any speed improvements with #183

**Comment by jonititan** [comment]
Ah that's a pity.  Did that include when using the speeds suggested by [Vincent Foley?](https://vfoley.xyz/reasonable-use-2/).
It's impressive how program structure changes can yield speed increases.

**Comment by marklit** [comment]
@jonititan it didn't. I did try to implement lazy statics into the code but my Rust skills weren't strong enough to get it to work.
