### ISSUE TITLE
First class aggregate support

### ISSUE THREAD

**Issue by Hoverbear** [zombodb/pgx#194]
Inspired by #102 .

Users wishing to create [aggregate functions](https://www.postgresql.org/docs/current/functions-aggregate.html) with `pgx` can get **most** of the way there without a custom SQL block.

What they do need a SQL block for, is something like:

```sql
CREATE AGGREGATE DEMOAVG (integer) (
    sfunc = integer_avg_state_func,
    stype = IntegerAvgState,
    finalfunc = integer_avg_final_func,
    initcond = '0,0'
);
```

As seen in the [`pgx-examples/aggregate/src/lib.rs`](https://github.com/zombodb/pgx/blob/develop/pgx-examples/aggregate/src/lib.rs#L70-L80) file.

The syntax for [`CREATE AGGREGATE`](https://www.postgresql.org/docs/current/sql-createaggregate.html) notably includes:

* The argument of the aggregate (`integer` here).
    * We can have the use specify this as a Rust type, or string of SQL representing a type.
    * The Postgres docs state to pass `*` here to accept none, we could copy this.
* The `initcond` allows users to set an initial condition (state).
    * We could support via primitive or a `const fn`.
* `sfunc` and `finalfunc` (optional) are references to the related functions.
    * We will want to let users specify Rust functions or a string pointing to a SQL function.
* `PARALLEL = { SAFE | RESTRICTED | UNSAFE }` similar to our extern function support.

There are several other options, and while it is not required that we support all of them, we should consider which others to support, and design the code to be able to adapt to new options easily.

# Syntax

We could support this via a macro in a direct, simple form:

```rust
#[derive(Copy, Clone)]
#[pgvarlena_inoutfuncs]
#[postgres_aggregate(
    sfunc = integer_avg_state_func, // or `"my_sql_state_func"`
    finalfunc = integer_avg_final_func, // or `"my_sql_final_func"`
    initcond = '0,0',
    arg_data_type = i32, // or `"integer"`
)]
pub struct IntegerAvgState {
    sum: i32,
    n: i32,
}
```

Since #165 allows us to include the results of things like `const fn`s or `const`s in our SQL, we could also support like:

```rust
initcond = my_const_fn()
```

Or:

```rust
initcond = MY_CONST_VALUE
```

We could also consider providing a trait, which, if `postgres_aggregate` was used without any options, could look something like this:

```rust
#[derive(Copy, Clone)]
#[pgvarlena_inoutfuncs]
#[postgres_aggregate]
pub struct IntegerAvgState {
    sum: i32,
    n: i32,
}

impl PostgresAggregate for IntegerAvgState {
    const INITIAL_CONDITION: Self = Self { sum: 0, n: 0 };
    type ARG_DATA_TYPE: i32;
    fn state_function(&self, v: Self::ARG_DATA_TYPE) -> Self {
        todo!()
    }
}
```

However the question of how to handle optional values like `finalfunc` gets murky. The macro-attributes are more flexible.

@eeeebbbbrrrr and I discussed using a proc macro on an impl block, like so:

```rust
trait PostgresAggregate where Self: Sized {
    type Arg;
    type Finalize;
    type MovingState;

    fn state(&self, v: Self::Arg) -> Self;

    fn finalize(&self) -> Self::Finalize {
        unimplemented!("pgx stub, define in impls")
    }

    fn combine(&self, other: Self) -> Self {
        unimplemented!("pgx stub, define in impls")
    }
    
    fn serial(&self) -> Vec<u8> {
        unimplemented!("pgx stub, define in impls")
    }

    fn deserial(&self, buf: Vec<u8>, internal: Internal<Self>) -> Internal<Self> {
        unimplemented!("pgx stub, define in impls")
    }

    fn moving_state(mstate: Self::MovingState, v: Self::Arg) -> Self::MovingState {
        unimplemented!("pgx stub, define in impls")
    }

    fn moving_finalize(mstate: Self::MovingState) -> Self::Finalize {
        unimplemented!("pgx stub, define in impls")
    }

}

#[derive(Copy, Clone, PostgresType)]
#[pgvarlena_inoutfuncs]
pub struct IntegerAvgState {
    sum: i32,
    n: i32,
}

#[pg_aggregate(
  parallel = Safe,
  initial_condition = "1,2",
  moving_initial_condition = "1,2",
  sort_operator = "example",
)]
impl PostgresAggregate for IntegerAvgState {
    type Arg = i32;
    type Finalize = i32;
    type MovingState = ();

    fn state(&self, v: Self::Arg) -> Self {
        todo!()
    }

    //#[pgx(finalfunc_modify = READ_ONLY)]
    fn finalize(&self) -> Self::Finalize {
        self.sum / self.n
    }
}
```

This seems like a nice way to "feel" rusty while also being able to tell if the user specified optional things like `finalfunc`.

Since we are using a proc macro here, we can intelligently add items like `finalize` with stubs if they are not present.

**Comment by JLockerman** [comment]
@Hoverbear Monday and Tuesday are going to be very busy next week, doe Wednesday work? (I still need to test out the rest of the beta with Toolkit also, which I was planning to start then, so I may run into issues there as well)
