### ISSUE TITLE
(develop)(sql-generator) not working with `cargo pgx schema` but works with `cargo pgx package`

### ISSUE THREAD

**Issue by comdiv** [zombodb/pgx#207]
1. create new extension with `cargo pgx new`
2. set dependencies to local `pgx` to use develop
3. call `cargo pgx schema` - it generates bin/sql-generator, but
`"cargo" "build" "--bin" "sql-generator" "--features" "pg12" "--no-default-features"`
` Discovered 0 SQL entities: 0 schemas (0 unique), 0 functions, 0 types, 0 enums, 0 sqls, 0 ords, 0 hashes`
4. call `cargo pgx package`
`"cargo" "build" "--bin" "sql-generator" "--release" "--features" "pg12" "--no-default-features"`
`Discovered 3 SQL entities: 1 schemas (1 unique), 2 functions, 0 types, 0 enums, 0 sqls, 0 ords, 0 hashes`

The only thing is --release - all other parameters are same

**Comment by comdiv** [comment]
And i don't set pg12 feature
```
 Creating required file `src/bin/sql-generator.rs` for SQL bindings
    Building SQL generator with features `pg12`
```
while:

```
[features]
default = []
pg10 = ["pgx/pg10", "pgx-tests/pg10" ]
pg11 = ["pgx/pg11", "pgx-tests/pg11" ]
pg12 = ["pgx/pg12", "pgx-tests/pg12" ]
pg13 = ["pgx/pg13", "pgx-tests/pg13" ]
pg_test = []

[dependencies]
pgx = { path = "../../../pgx/pgx", no-default-features=true }
pgx-macros = { path="../../../pgx/pgx-macros"}
murmur3 = "0.5.1"
serde = "1.0.130"
```

**Comment by comdiv** [comment]
Check it more well

lib.rs
```
use pgx::*;

pg_module_magic!();

#[pg_extern]
fn hello_test2() -> &'static str {
    "Hello, test2"
}
```
works!


split to 
```
use pgx::*;

pg_module_magic!();

pub mod ids;
```

```
use pgx::*;


#[pg_extern]
fn hello_test2() -> &'static str {
    "Hello, test2"
}
```

and it will be not working for `cargo pgx schema` only for `cargo pgx package`

**Comment by Hoverbear** [comment]
Hi! What OS is this?

**Comment by Hoverbear** [comment]
Noting @comdiv reports this is linux mint.

**Comment by Hoverbear** [comment]
Setting this in the `Cargo.toml` resolves the issue! We'll reflect it in release.

```toml
[profile.dev]
panic = "unwind"
lto = "thin"
```
