### ISSUE TITLE
PgTupleDesc exposes UB to safe code

### ISSUE THREAD

**Issue by dtolnay** [zombodb/pgx#222]
```rust
pgx::tupdesc::PgTupleDesc::from_pg_copy(0xdeadbeefusize as _);
```

This results in an out of bounds read at https://github.com/postgres/postgres/blob/48064a8d330db259076fb7b2300544fbf65f4109/src/backend/access/common/tupdesc.c#L154, which is UB. In general it is unsound for a safe API to result in UB.

**Comment by eeeebbbbrrrr** [comment]
hey, lets make a deal.  I'm on vacay for two weeks (gettin' married).  When I get back, give me a few days to write code to detect all these and fix them, and then you can get back into your groove against that.

And sincerely, thank you sooo much for whatever it is you're doing to find these problems.  `pgx` was my literal first Rust project and I had some fundamental misunderstandings around `unsafe`.  I want to fix all these, and I think I can do it all in one fell swoop (I fixed a bunch today, but I guess there's more).

Anyways, we're on it and generally aware of the issues here.

Big love...

eric

<img width="980" alt="Screen Shot 2021-09-24 at 4 33 17 PM" src="https://user-images.githubusercontent.com/5117238/134746249-f798330a-9b24-4574-a94e-d322753a64ea.png">

**Comment by Hoverbear** [comment]
@eeeebbbbrrrr gonna get married. :)

**Comment by eeeebbbbrrrr** [comment]
> @eeeebbbbrrrr gonna get married. :)

and only for the first time!
