### ISSUE TITLE
Using PGX to create a postgres index

### ISSUE THREAD

**Issue by thoward27** [zombodb/pgx#271]
Apologies if this is written down somewhere already, I couldn't put my finger on anything concrete.

I am looking to understand how to use PGX to create a postgres index. Any tips/tricks/**simple** examples would be greatly appreciated.

Best,
Tom

**Comment by eeeebbbbrrrr** [comment]
There are no simple examples.  @zombodb does this, but in total it's >25k LOC.

What I'd suggest is studying the C source for one of the more simple built-in Postgres indexes (maybe the BRIN index), and of course read the Postgres developer docs for implementing a custom Index AM.

It's straightforward to get the skeleton API compiling.  Then it's just a simple matter of programming.  :)
