### ISSUE TITLE
Controlling load order

### ISSUE THREAD

**Issue by ccleve** [zombodb/pgx#318]
The new sql-generator works a bit differently than the old system. How do I control the order in which automatically-generated SQL executes?

I am creating an operator inside a `\\\ ```pgxsql` block, similar to the way Zombo does it in opclass.rs. This operator depends on a type defined elsewhere. I'm getting an error because the CREATE OPERATOR line is getting executed before the CREATE TYPE.

**Comment by eeeebbbbrrrr** [comment]
I'd like to see your code, but you can do:

```rust
#[pg_operator(requires = TheRequiredType)]
... other #[attributes]
fn the_fn() {
    ...
}
```

If this doesn't help, please feel free to re-open with more details.
