### ISSUE TITLE
Race condition in running cargo test

### ISSUE THREAD

**Issue by iskakaushik** [zombodb/pgx#319]
Steps to reproduce:

1. Create a new project.
2. `cargo pgx test v13`
3. Sometimes the test fails. Without any meaningful logs, see below for example logs.

Removing the `.so` file from `~/.pgx/13.5/pgx-install/lib/postgresql/<extension_name>.so`, causes the shared object file to regenerate which causes the test run to succeed. But this periodically fails again. Removing the file is one way to fix it.

This seems like a case where the copy at https://github.com/zombodb/pgx/blob/2a15b6d62c0f61ddcd80fe6b229cd56ae4c2c6dd/cargo-pgx/src/commands/install.rs#L48 isn't waiting for the build to complete.

```
[2021-12-07 17:21:45.261 EST] [95410] [61afde79.174b2]: LOG:  listening on IPv6 address "::1", port 32213
[2021-12-07 17:21:45.262 EST] [95410] [61afde79.174b2]: LOG:  listening on IPv4 address "127.0.0.1", port 32213
[2021-12-07 17:21:45.262 EST] [95410] [61afde79.174b2]: LOG:  listening on Unix socket "/Users/kaushik/.pgx/.s.PGSQL.32213"
[2021-12-07 17:21:45.263 EST] [95411] [61afde79.174b3]: LOG:  database system was shut down at 2021-12-07 17:21:45 EST
     Creating database pgx_tests
thread 'tests::pg_test_hello_testex_rust' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }', /Users/kaushik/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.5/src/framework.rs:486:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: pgx_tests::framework::create_extension
             at /Users/kaushik/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.5/src/framework.rs:481:5
   5: pgx_tests::framework::initialize_test_framework
             at /Users/kaushik/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.5/src/framework.rs:173:9
   6: pgx_tests::framework::run_test
```

**Comment by eeeebbbbrrrr** [comment]
oh, this is super interesting.

I can't tell you how many times I've run `cargo pgx test` across all sorts of computers with 1 to 64 cpus and I've never seen this.

Neat.

I'll noodle it tomorrow.  Thanks for the report.

**Comment by eeeebbbbrrrr** [comment]
I've been running `$ while true; do cargo pgx test pg13; done` for the past 30 minutes or so without any failures.

The "compile & install extension" bit of `cargo pgx test` happens under a locked Mutex, so I'm not super sure that your theory is correct.  https://github.com/zombodb/pgx/blob/a4c63084dceb353cf1cc397ad5bd5021611915c4/pgx-tests/src/framework.rs#L156-L180

The error indicates that the `CREATE EXTENSION extname;` statement failed, and sadly the underlying Postgres error is being lost.

I'm not exactly sure what to do here.  Any other information you can provide?  Details about your system might be interesting.  Based on file paths, I assume you're on MacOS (so am I)?

**Comment by iskakaushik** [comment]
Got it. Thanks for trying to reproduce it. I am able to semi-consistently reproduce this, and the code pointer is helpful. I will attempt to put some additional logging into place to validate / debunk my theory. I'm unfamiliar with the issue etiquette for this repository, but I will close this issue and re-open once I have additional actionable data.

**Comment by eeeebbbbrrrr** [comment]
It's a weird one.  Improving the error reporting from:

https://github.com/zombodb/pgx/blob/a4c63084dceb353cf1cc397ad5bd5021611915c4/pgx-tests/src/framework.rs#L478-L487

would probably help a ton in hunting this down.

**Comment by Hoverbear** [comment]
We noted this may be caused by #328
