### ISSUE TITLE
'operators' example does not appear to work

### ISSUE THREAD

**Issue by mpalmer** [zombodb/pgx#320]
I'm getting started with pgx and I'm blown away by how powerful it is.  However, I'm collapsing at the first hurdle: I can't even make the examples work.  The extension I plan to write creates a custom type, with the usual crop of operators derived from my struct, so I tried building on the `operators` example.  However, before I even get to making any changes, the example doesn't work (at least for Postgres 12 and Rust 1.56.1).  It builds fine, but when I try to actually use it, I get the following:

```
$ cargo pgx run pg12
[...]
operators=# create extension operators;
ERROR:  operator does not exist: thing = thing
operators=# 
```

On the off chance that the problem was something in my local environment, I did a complete "clean room" test as follows:

1. Fire up a clean Docker container from the basic Rust image, so we know there's nothing unusual getting in the way:
    ```
    docker run --rm -it rust:1.56.1-buster
    ```
2. Install some extra packages:
    ```
    apt-get install clang
    ```

3. Create a non-privileged user (because `initdb` is not friends with running as root) and switch to it, with a sane `PATH` and other env vars rust desires:
    ```
    adduser pgx --gecos '' --disabled-password
    su - pgx
    PATH="/usr/local/cargo/bin:$PATH"
    export RUSTUP_HOME=/usr/local/rustup
    ```
2. Clone pgx, install `cargo-pgx` in the usual fashion, and do the `init` dance (pg12 only, because that's all I'm targeting at the moment, and we don't care to burn more CPU than necessary):
    ```
    git clone https://github.com/zombodb/pgx.git
    cd pgx
    cargo install cargo-pgx
    cargo pgx init --pg12 download
    ```
3. Wander into the appropriate example project, and give it a run:
    ```
    cargo pgx run pg12
    ```
4. Wait for a while, end up dropped in a `psql` prompt.  Try to load the extension:
    ```
    create extension operators;
    ```
5. Note that we get a rather discouraging error message, that looks like this:
    ```
    ERROR:  operator does not exist: thing = thing
    ```
6. Be sad :panda_face:, write bug report.

... which brings us to now.  Am I doing something incredibly bone-headed in my repro above, or is there an actual problem in the examples and/or pgx that needs fixinating?

**Comment by eeeebbbbrrrr** [comment]
Don’t be sad. 

pgx just went through a pretty major upgrade to its schema generator and it’s possible we either missed this example entirely or we’ve got a bug or two. 

I’ll try to look into it later today.

**Comment by eeeebbbbrrrr** [comment]
Yeah, we're emitting bits of the schema in the wrong order.  I'm scratching my head now about how to fix it.

**Comment by mpalmer** [comment]
Glad to hear that the problem's fairly straightforward. Let me know if I can be of any help.

**Comment by eeeebbbbrrrr** [comment]
The above commit fixes it for me locally.  I'll work on getting a new release published this evening.  Thanks for the report.

**Comment by eeeebbbbrrrr** [comment]
For the record… mad props to @Hoverbear for the new schema generator. Having a legit dependency graph is super amazing and makes fixing little logic bugs like this very simple.

**Comment by eeeebbbbrrrr** [comment]
Okay, this has been published to crates.io.  Thanks again for the report.  You're **really** gonna like pgx' automatic operator support.  It's really slick.

**Comment by mpalmer** [comment]
Thanks for the blazing fast turnaround.  I do, indeed, like the automatic operator support, just from the docs.  Looking forward to trying it out for realsies!
