### ISSUE TITLE
Derive extension version from Cargo.toml

### ISSUE THREAD

**Issue by JamesGuthrie** [zombodb/pgx#344]
Currently the extension's version number is derived from the `default_version` field of the `.control` file. The extension is also versioned in `Cargo.toml`. It would be convenient to only have to version the extension in `Cargo.toml` and have that version flow through into the generated `.control` file.

**Comment by Hoverbear** [comment]
It's now there via `@CARGO_VERSION@`. Thanks @JamesGuthrie :)
