### ISSUE TITLE
Calling pgx as a library

### ISSUE THREAD

**Issue by ccleve** [zombodb/pgx#363]
It's turning out to be a lot easier to write a portion of the code in my project in C and a portion in Rust. The main code to interface with Postgres is C and the interesting parts are in Rust. This is the way Timescale does it (https://blog.timescale.com/blog/introducing-hyperfunctions-new-sql-functions-to-simplify-working-with-time-series-data-in-postgresql/), except that they have two completely separate extensions.

I'd like to link to the pgx-generated code as a static library, so I only have to distribute a single extension. (I'll copy the schema sql into the main project by hand). I'm able to generate a static lib, link it, and call a function in it, but I get this error message:

```
select hello_myextension();
ERROR:  functions under #[pg_guard] cannot be called from threads
CONTEXT:  <unknown>:0:0
```

The pgx code is plain-vanilla:
```
#[pg_extern]
fn hello_myextension() -> &'static str {
    "Hello, myextension"
}

```
Any workarounds?

**Comment by Hoverbear** [comment]
So this is triggered by here:

https://github.com/zombodb/pgx/blob/a4c63084dceb353cf1cc397ad5bd5021611915c4/pgx-macros/src/rewriter.rs#L536-L538

Which is a thread local:

https://github.com/zombodb/pgx/blob/a4c63084dceb353cf1cc397ad5bd5021611915c4/pgx-pg-sys/src/submodules/guard.rs#L70

Set via

https://github.com/zombodb/pgx/blob/a4c63084dceb353cf1cc397ad5bd5021611915c4/pgx/src/lib.rs#L459-L471

I think if you ensure that is called first, you should be ok!

**Comment by ccleve** [comment]
Yes! This works.

In my main C project, I add this:

```
void fixthread(void);
void _PG_init(void)
{
    fixthread();
}
```

And in my pgx project, I add this in lib.rs:

```
#[no_mangle]
pub extern "C" fn fixthread() {
    initialize();
}
```

You might want to add this little trick to the documentation.
