### ISSUE TITLE
Schema generation broken with old GCC

### ISSUE THREAD

**Issue by jamessewell** [zombodb/pgx#371]
I have been (unfortunately) using an old CentOS 7.2 machine to compile a PGX extension (as I need GLIBC 2.18). 

Once I got the correct version of clang on there (using `scl enable llvm-toolset-7`) things compiled, and worked - but I couldn't get anything other than an empty schema file with no SQL in it.

It seems the issue was my old (4.8.5) GCC. Using a newer version (7.3.1, via `scl enable devtoolset-7`) seems to fix this issue.

I'm not sure exactly where GCC changes and this starts working - but can something be added to the README?

**Comment by Hoverbear** [comment]
Thanks for this bug report @jamessewell :)
