### ISSUE TITLE
Autocompletion for `pg_sys` crate members

### ISSUE THREAD

**Issue by iskakaushik** [zombodb/pgx#378]
When I try to go-to definition of members of a struct like so:

<img src="https://user-images.githubusercontent.com/1006071/149604641-69e8b8ff-b0ca-43a0-9777-02fb5abf524b.png" width=400 />

I end up here: 

<img src="https://user-images.githubusercontent.com/1006071/149604666-6e787417-9e01-43f7-bc7c-5b3f26506061.png" width=400 />

This isn't very useful as I'd like to have jumped into the definition of `RangeTableEntry` struct in the above example. I tried to get this working with both vscode and intellij and failed.

What is the recommended IDE setup for consumers of `pgx`?

Thanks in advance.

**Comment by eeeebbbbrrrr** [comment]
We tried our best to answer your question on discord.  If you find something that works well for you, please consider sending us a PR to document it.  We'd be thrilled to accept it!

**Comment by sumerman** [comment]
Setting a default feature to one of the configured postgres features did it for me. E.g.:
```toml
[features]
default = ["pg14"]
```
