### ISSUE TITLE
Request for an example for an SRF returning a SETOF RECORD with variable columns

### ISSUE THREAD

**Issue by iskakaushik** [zombodb/pgx#379]
I'm attempting to write a set returning function that returns a set of records.  In a traditional extension I could do something along the lines of:

```
CREATE OR REPLACE FUNCTION example_srf
    RETURNS SETOF record
    LANGUAGE C
AS 'MODULE_PATHNAME', $$example_srf_impl$$;
```

And return records in the implementation.

The problem I'm attempting to solve is to have a function return a set of records and the number of columns a function call returns depends on its input arguments.

Thanks

**Comment by eeeebbbbrrrr** [comment]
I'm not even sure this is possible in C.  Postgres needs to know the type of all things being returned, so having a dynamically-determined type wouldn't be feasible.  `record` is even declared as a pseudo-type:

```
#  \dT pg_catalog.record
                        List of data types
   Schema   |  Name  |                 Description                 
------------+--------+---------------------------------------------
 pg_catalog | record | pseudo-type representing any composite type
```

See also here:

https://www.postgresql.org/docs/14/plpgsql-declarations.html#PLPGSQL-DECLARATION-RECORDS

If you have a more concrete example of what you've done in the past with `RETURNS record`, I'm happy to investigate further.
