### ISSUE TITLE
Can this be used to create custom text search parser?

### ISSUE THREAD

**Issue by messense** [zombodb/pgx#38]
I am thinking about creating a text search parser base on https://github.com/messense/jieba-rs with pgx.

**Comment by zombodb** [comment]
Hi.  Yeah, I don't see why not.  Anything that you might could do with Postgres' C API you can do with `pgx`.  `pgx` may not have safe wrappers around everything, but it's all there to be used.

**Comment by eeeebbbbrrrr** [comment]
I’m going to close this but feel free to ask any other questions either where or in a new issue.
