### ISSUE TITLE
Speed up sql-generator

### ISSUE THREAD

**Issue by ccleve** [zombodb/pgx#391]
I wrote about this in #287, but I think it's better to have a dedicated issue.

Compiling sql-generator is really, really slow, about 25 seconds on my Mac Mini. I've been researching it, and here's what I have so far:

1. Using Rust nightly with the -Z timings flag shows that almost all of the time is consumed by the linker.
 
2. Using [cargo bloat](https://github.com/RazrFalcon/cargo-bloat) confirms this, and shows a ton of dependencies.

3. I tried to spin up a server on AWS to see if throwing hardware at the problem would solve it, but using a large compute-optimized box was actually slower. My guess was that because the link process has to fetch a large number of small files from disk, it was actually EBS that was slow. I have not tried a box with a local disk to confirm this.

4. I tried a [faster linker, zld](https://github.com/michaeleisel/zld). No improvement.

5. I thought that maybe incremental linking would help. I added .cargo/config.toml to the project, with:
```
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-r"]

```
The -r flag apparently enables so kind of incremental linking. But I get the error message `note: ld: -r and -dead_strip cannot be used together`. Apparently this comes from a generated pgx-linker-script.sh. I haven't figured out how to modify this script.

So that's where I'm at. If someone who knows more than me can figure out incremental linking we can make some progress.

**Comment by Hoverbear** [comment]
Hi @ccleve , 

You can edit the script in `.cargo/pgx-linker-script.sh`.  I don't think we're passing `-dead_strip` in our script.

25 seconds is quite a bit slower than we expect, yes. Do you think you could upload that timings file? 

This is debug? I think 25s in release would be a bit unsurprising.

Before 0.2.0 we were actually reading the source code and parsing it with `syn` and `quote`. This lead to a number of issues such as not being able to capably handle things like macros without becoming a rust compiler ourselves. This solution is more robust, but slow. :(

**Comment by ccleve** [comment]
Thanks. The only pgx-linker-script.sh file I have on my system is in pgx/cargo-pgx/src/templates. Is that what I should edit? You're right that it does not contain -dead_strip. I wonder where it is coming from?

Oddly, my builds have become much slower. I don't know what changed.

I can't now recreate the report that told me that the linker was slow, so ignore that for the moment.

I ran `"cargo" "build" "--bin" "sql-generator" "--features" "pg14" "--no-default-features" -Z timings` and it didn't show anything in the output of significance, unfortunately.

I ran `cargo bloat --time` on my project and unfortunately, it insists on running a `cargo clean` first, which makes the output useless.

I set `RUSTFLAGS="-Z time-passes"` before doing a build and got slightly more useful output. Attached. It looks like the process of compiling sql-generator somehow touches 172 crates. I'm not sure what it's doing to each crate, but whatever it is, it's really time-consuming.

Yes, everything I'd doing is in debug mode. Release mode takes three times longer.

[sqlgentimings.txt](https://github.com/zombodb/pgx/files/7928176/sqlgentimings.txt)

**Comment by Hoverbear** [comment]
Your extension should have a `.cargo` folder with a `pgx-linker-script.sh` in it. You might also be able to try `mold`.

We can certainly make some changes to improve the speed of the sql-generator crate link. We've kept a lot of debugging in it for the first few releases to work out the issues.

**Comment by ccleve** [comment]
Aha! My extension was missing the automatically-generated .cargo folder. I ran cargo pgx new to create one.

`mold` is not stable on Mac, unfortunately.

As a test, I created a completely new, plain-vanilla extension with `cargo pgx new`. I compiled it once with `cargo pgx run pg14`, then made a tiny change to lib.rs to trigger a schema change, then compiled again. It took 17 seconds to build sql-generator. How long does it take on your system?

**Comment by Hoverbear** [comment]
I usually see it take 8 or so seconds. Which I think is still more than I'd like. If you're not changing the structure of your code, just the logic, you can try using `--no-schema` to avoid the sql-generator step.

**Comment by Hoverbear** [comment]
I tried removing a bunch of the sql-generator dependencies and didn't see significant (or even really measurable) speedup, since they were all already pgx dependencies. I'm poking other ideas.

**Comment by Hoverbear** [comment]
#441 should improve your build times dramatically. :)

**Comment by ccleve** [comment]
Outstanding. Looking forward to trying it.

**Comment by Hoverbear** [comment]
These improvements landed in the 0.4.0-beta and will soon be in a full release. Thanks for your report. :)

**Comment by ccleve** [comment]
Just to close this out, 0.3.3 took 5 seconds to compile my app and 25-28 seconds to run sqlgenerator.

0.4.0-beta takes 18 seconds to do both together.

**Comment by Hoverbear** [comment]
It's getting even better:

```bash
ana@autonoma:~/git/zombodb/zombodb$ RUST_LOG=cargo_pgx::command cargo pgx schema --skip-build > foo.sql
 Discovering SQL entities
  2022-03-11T18:05:37.913686Z DEBUG cargo_pgx::command::schema: Found existing stub file
    at cargo-pgx/src/command/schema.rs:428
    in cargo_pgx::command::schema::create_stub with symbols: 9816, rs_dest: /home/ana/.pgx/postmaster_stubs/home/ana/.pgx/14.1/pgx-install/bin/postmaster_stub.rs, so_dest: /home/ana/.pgx/postmaster_stubs/home/ana/.pgx/14.1/pgx-install/bin/postmaster_stub.so
    in cargo_pgx::command::schema::generate_schema with pg_version: 14.14, release: false, test: false, features: []
    in cargo_pgx::command::schema::execute

  2022-03-11T18:05:37.913739Z DEBUG cargo_pgx::command::schema: Found existing stub shared object
    at cargo-pgx/src/command/schema.rs:460
    in cargo_pgx::command::schema::create_stub with symbols: 9816, rs_dest: /home/ana/.pgx/postmaster_stubs/home/ana/.pgx/14.1/pgx-install/bin/postmaster_stub.rs, so_dest: /home/ana/.pgx/postmaster_stubs/home/ana/.pgx/14.1/pgx-install/bin/postmaster_stub.so
    in cargo_pgx::command::schema::generate_schema with pg_version: 14.14, release: false, test: false, features: []
    in cargo_pgx::command::schema::execute

  Discovered 323 SQL entities: 37 schemas (2 unique), 248 functions, 5 types, 22 enums, 11 sqls, 0 ords, 0 hashes, 0 aggregates
  2022-03-11T18:05:37.957388Z DEBUG cargo_pgx::command::schema: Collecting 323 SQL entities
    at cargo-pgx/src/command/schema.rs:323
    in cargo_pgx::command::schema::generate_schema with pg_version: 14.14, release: false, test: false, features: []
    in cargo_pgx::command::schema::execute

     Writing SQL entities to /dev/stdout
```

0.06 seconds. :)
