### ISSUE TITLE
`cargo pgx schema` creates sql schema file with one `-`

### ISSUE THREAD

**Issue by JamesGuthrie** [zombodb/pgx#438]
Postgres expects SQL schema files be named in the following form:

`<extension>--<version>.sql`

In general, pgx produces sql files following this naming scheme. For
some reason, `cargo pgx schema` does not. Instead, it produces a file
in the form of:

`<extension>-<version>.sql`

**Comment by Hoverbear** [comment]
In 0.4.0-beta `cargo pgx schema` writes to stdout unless explicitly told a file, so this is resolved.
