### ISSUE TITLE
Do you have an example of how to deal with null inputs

### ISSUE THREAD

**Issue by davecramer** [zombodb/pgx#454]
How does one replicate
```
 if (PG_ARGISNULL(0) ) {
        PG_RETURN_NULL();
    }
```

`return Option::None; `
is somewhat obvious, but how do you check the incoming argument is null ?

**Comment by Hoverbear** [comment]
Generally your function you'd do like:

```rust
fn floof(x: Option<i32>) {
    if x.is_none() {
        panic!("Oh no");
    }
}
```

**Comment by davecramer** [comment]
thx...
how to get a str out of x ?

**Comment by Hoverbear** [comment]
```rust
fn floof(x: Option<i32>) {
    if let Some(inner_of_x) = x {
        panic!("Look, a {}", inner_of_x);
    }
}

fn floof2(x: Option<i32>) {
    let inner_of_x = x.unwrap_or("There was nothing there, this panics.")
}
```

There are lots of ways to work with [`std::option::Option`](https://doc.rust-lang.org/std/option/index.html), I suggest getting familiar because you'll use it a lot.

**Comment by Hoverbear** [comment]
Closing, feel free to re-open if you have more questions. :)

**Comment by davecramer** [comment]
thx, appreciate it. I'm trying to learn pgx and rust at the same time :)

**Comment by eeeebbbbrrrr** [comment]
Hey Dave!  Happy to see you exploring pgx.

We have a number of basic examples over at https://github.com/zombodb/pgx/tree/master/pgx-examples.  A number of them have links to corresponding twitch streams I did for them.

pgx also exposes quite a number of the `PG_XXX()` macros as inlined functions:  https://docs.rs/pgx/0.3.3/pgx/fcinfo/index.html

So for example, you *could* go a little more low-level and do something like this:

```rust
/// ```pgxsql
/// CREATE FUNCTION use_string(text) RETURNS text LANGUAGE c AS 'use_string_wrapper';
/// ```
#[pg_extern]
fn use_string(fcinfo: pg_sys::FunctionCallInfo) -> pg_sys::Datum {
   match pg_getarg::<&str>(fcinfo, 0) {
      Some(s) => {
         log!("got {}", s);
         return format!("Thanks for the '{}'", s).into_datum().unwrap();
      }
      None => {
         log!("got NULL");
         return pg_return_null();  
   }
}
```

But that's quite a bit more effort than simply doing...

```rust
#[pg_extern]
fn use_string(s: Option<&str>) -> Option<String> {
    s.map_or(None, |s| Some(format!("Thanks for the 's' {}", s)))
}
```
... and you don't need to write the `CREATE FUNCTION` statement -- pgx will do it for you.

Behind the scenes, pgx is essentially writing the former for you when you write the latter.

Regarding the examples, I bet you'll find the [srf](https://github.com/zombodb/pgx/tree/master/pgx-examples/srf) example fun.
