### ISSUE TITLE
v0.4.0-beta.0 not finding C function

### ISSUE THREAD

**Issue by ccleve** [zombodb/pgx#469]
My project compiles fine under 0.3.3. It makes direct reference to some Postgres functions. Here's an example:

```
extern "C" {
    pub fn BufFileCreateTemp(interXact: bool) -> *mut BufFile;
}
```
and in another file:
```
// first, create the file if necessary
if self.buffile == None {
    unsafe { self.buffile = Option::from(BufFileCreateTemp(false)); }
}
let buffile = self.buffile.unwrap();
```

I followed all of the upgrade instructions for v0.4.0-beta.0, did a `cargo clean`, then this:

```
 cargo pgx run pg14
building extension with features `pg14`
"cargo" "build" "--features" "pg14" "--no-default-features" "--message-format=json-render-diagnostics"
   Compiling relevantdb v0.0.0 (/Users/ccleve/Documents/dev/pg/RelevantDB)
    Finished dev [unoptimized + debuginfo] target(s) in 18.08s

installing extension
     Copying control file to /Users/ccleve/.pgx/14.1/pgx-install/share/postgresql/extension/relevantdb.control
     Copying shared library to /Users/ccleve/.pgx/14.1/pgx-install/lib/postgresql/relevantdb.so
    Building for SQL generation with features `pg14`
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
 Discovering SQL entities
  Discovered 24 SQL entities: 0 schemas (0 unique), 19 functions, 4 types, 0 enums, 1 sqls, 0 ords, 0 hashes, 0 aggregates
The application panicked (crashed).
Message:  Couldn't libload /Users/ccleve/Documents/dev/pg/RelevantDB/target/debug/librelevantdb.dylib: DlOpen { desc: "dlopen(/Users/ccleve/Documents/dev/pg/RelevantDB/target/debug/librelevantdb.dylib, 0x0001): symbol not found in flat namespace \'_BufFileCreateTemp\'" }
Location: /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/schema.rs:385

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::schema::generate_schema with pg_version=14.14 release=false test=false path=/Users/ccleve/.pgx/14.1/pgx-install/share/postgresql/extension/relevantdb--1.0.sql features=["pg14"]
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/schema.rs:120
   1: cargo_pgx::command::install::install_extension with pg_version=14.14 release=false test=false features=["pg14"]
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/install.rs:67
   2: cargo_pgx::command::run::run_psql with pg_version=14.14 release=false
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/run.rs:87
   3: cargo_pgx::command::run::execute
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/run.rs:39

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 10 frames hidden ⋮                              
  11: cargo_pgx::command::schema::generate_schema::h4f3da941c3eca4cc
      at <unknown source file>:<unknown line>
  12: cargo_pgx::command::install::install_extension::hd179c7c4929bfb5f
      at <unknown source file>:<unknown line>
  13: <cargo_pgx::command::run::Run as cargo_pgx::CommandExecute>::execute::h3f1f7173ec7cefd4
      at <unknown source file>:<unknown line>
  14: cargo_pgx::main::h86f79c05b141861f
      at <unknown source file>:<unknown line>
  15: std::sys_common::backtrace::__rust_begin_short_backtrace::h4387a848710e2a57
      at <unknown source file>:<unknown line>
  16: std::rt::lang_start::{{closure}}::he62ac3dff73c36f4
      at <unknown source file>:<unknown line>
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4dd0f8c7b850f348
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:259
  18: std::panicking::try::do_call::h87be4eed64f35c01
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406
  19: std::panicking::try::hff817004c8a737c1
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370
  20: std::panic::catch_unwind::h6d209170f63e98ac
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133
  21: std::rt::lang_start_internal::{{closure}}::h0168cc1e28682b0d
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128
  22: std::panicking::try::do_call::h8d63645390643972
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406
  23: std::panicking::try::h0ced96fd1d070610
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370
  24: std::panic::catch_unwind::h700c7180333c2e66
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133
  25: std::rt::lang_start_internal::h240e1720b3cdfa5e
      at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128
  26: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.



```

**Comment by Hoverbear** [comment]
Hi @ccleve , thanks for noticing this. You're right, this won't work. I'll think about this and have a fix before release.

**Comment by Hoverbear** [comment]
Hi @ccleve so we talked and we're just going to add those headers to `pgx-pg-sys`.

We're not really sure if we should be explicitly supporting possibly unsafe postgres bindings like that as later when we do bind them, you'll face issues.

**Comment by eeeebbbbrrrr** [comment]
Yes, what @Hoverbear said.  We'll get the headers for this function included in the upcoming 0.4.0 release, but in the future I think it's best if you find yourself writing `extern {}` blocks for a function pgx doesn't have a binding for, that we add it to pgx proper.  Little changes like that are things we can do in real time, so as to not hold up progress on our users end very much.

**Comment by ccleve** [comment]
Actually, I've changed my design a bit and won't be using BufFIle at all. 

But I do make many direct calls to C functions. I've been writing C code to talk to many pg functions (because sometimes that's just easier), compiling it using cc and generating bindings using bindgen. It works pretty well.

There are some things that are just not easy to do in Rust, particularly around buffers and forks and locking. A tiny bit of C with an extern call handles it efficiently.

Also, there are other things that may not be possible to do correctly in Rust at all, particularly around the use of atomics.

What if there is a third-party library written in C, and the extension needs to talk to it? Is this possible in 0.4.0?

**Comment by eeeebbbbrrrr** [comment]
> What if there is a third-party library written in C, and the extension needs to talk to it? Is this possible in 0.4.0?

I believe this will be just fine if you a) statically link that little library, or even b) just dynamically link to it.

The problem here is that the **postgres** symbols aren't available to us when we generate the schema as the extension was linked with `["-C", "link-args=-Wl,-undefined,dynamic_lookup"]` (as it must be).  You should be totally fine using either your own or third-party libraries as they'll be linked "correctly".

What have further discussed, however, is to just make our little stub generator dig out all the symbols from the "postmaster.exe" binary, and not rely on our generated bindings.  This would let us load the extension.so during schema generation without any concern for (postgres) missing symbols.

**Comment by eeeebbbbrrrr** [comment]
> Also, there are other things that may not be possible to do correctly in Rust at all, particularly around the use of atomics.

Yah, no doubt.  pgx has a little "c shim" for wrapping various #define macros as functions.  It's statically linked with pgx.  I've tried to keep it as small as possible, but suspect we'll be expanding it over time.

**Comment by ccleve** [comment]
I can confirm that once I remove direct calls to pg functions, everything works fine. I can write my own wrapper functions for the pg functions and call them without a problem. This is probably a better way to do it anyway.

**Comment by eeeebbbbrrrr** [comment]
I'm gonna re-open this as there is an action we're gonna take that's come out of this discussion.

**Comment by ccleve** [comment]
Oops, I spoke too soon. Now I'm seeing a "symbol not found in flat namespace" error even when the pg symbol is referenced only within my own C code. I don't know how I managed to compile things before.

```
static BlockNumber get_free_block(Relation index) {
    BlockNumber blkno = GetFreeIndexPage(index); // marks page as used in the fsm
    return blkno;
}

```

Also, there's an oddity. I reran cargo pgx init to upgrade to pg 14.2. As you can see, it is copying the extension to the 14.2 directory. But in the SPANTRACE section below it says "cargo_pgx::command::schema::generate_schema with pg_version=14.14". It's not grabbing the right version. Not sure if that matters.


cargo pgx run pg14
building extension with features `pg14`
"cargo" "build" "--features" "pg14" "--no-default-features" "--message-format=json-render-diagnostics"
   Compiling relevantdb v0.0.0 (/Users/ccleve/Documents/dev/pg/RelevantDB)
    Finished dev [unoptimized + debuginfo] target(s) in 21.18s

installing extension
     Copying control file to /Users/ccleve/.pgx/14.2/pgx-install/share/postgresql/extension/relevantdb.control
     Copying shared library to /Users/ccleve/.pgx/14.2/pgx-install/lib/postgresql/relevantdb.so
    Building for SQL generation with features `pg14`
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
 Discovering SQL entities
  Discovered 24 SQL entities: 0 schemas (0 unique), 19 functions, 4 types, 0 enums, 1 sqls, 0 ords, 0 hashes, 0 aggregates
The application panicked (crashed).
Message:  Couldn't libload /Users/ccleve/Documents/dev/pg/RelevantDB/target/debug/librelevantdb.dylib: DlOpen { desc: "dlopen(/Users/ccleve/Documents/dev/pg/RelevantDB/target/debug/librelevantdb.dylib, 0x0001): symbol not found in flat namespace \'_GetFreeIndexPage\'" }
Location: /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/schema.rs:385

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::schema::generate_schema with pg_version=14.14 release=false test=false path=/Users/ccleve/.pgx/14.2/pgx-install/share/postgresql/extension/relevantdb--1.0.sql features=["pg14"]
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/schema.rs:120
   1: cargo_pgx::command::install::install_extension with pg_version=14.14 release=false test=false features=["pg14"]
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/install.rs:67
   2: cargo_pgx::command::run::run_psql with pg_version=14.14 release=false
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/run.rs:87
   3: cargo_pgx::command::run::execute
      at /Users/ccleve/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.4.0-beta.0/src/command/run.rs:39

**Comment by eeeebbbbrrrr** [comment]
> Oops, I spoke too soon. Now I'm seeing a "symbol not found in flat namespace" error even when the pg symbol is referenced only within my own C code.

Right.  This is the underlying issue that we're working to resolve.  You're referencing a postgres symbol that pgx doesn't (yet) know about -- doesn't matter if from Rust or C.

**Comment by eeeebbbbrrrr** [comment]
> Also, there's an oddity. I reran cargo pgx init to upgrade to pg 14.2. As you can see, it is copying the extension to the 14.2 directory. But in the SPANTRACE section below it says "cargo_pgx::command::schema::generate_schema with pg_version=14.14". It's not grabbing the right version. Not sure if that matters.

That sounds like a bug too.  I can't think of a reason why this would be right.  Thanks for catching it!

**Comment by Hoverbear** [comment]
@ccleve you might be able to use this checkout: https://github.com/zombodb/pgx/pull/478

It's pretty rough right now though, might want to let it merge.

**Comment by eeeebbbbrrrr** [comment]
18s in debug mode?  Is that a clean build?  What’s your line count?  ZDB doesn’t even take that long with 0.3.x on a clean release build and it’s 25k lines.

**Comment by ccleve** [comment]
Yes, debug mode. If I do a cargo clean first, it takes a couple of minutes to build. After that I can make a very small change to one file, run "cargo pgx run pg14" and it takes 18 seconds. The Clion Statistic plugin reports 884 lines of Rust, 152 lines of C. I disabled the C build code just to test and it did not improve the time (because it wasn't getting invoked after only a small change to the Rust code.)

My machine is a Mac Mini 2018, which seems to have adequate processor performance. 3 GHz 6-Core Intel Core i5. 8gb RAM, plenty of disk.

**Comment by eeeebbbbrrrr** [comment]
Ya know what. I’m a doofus. I read 18s but heard 18m.  Just ignore me. 

18 seconds seems reasonable

**Comment by eeeebbbbrrrr** [comment]
> Ya know what. I’m a doofus. I read 18s but heard 18m. Just ignore me.
> 
> 18 seconds seems reasonable

It’s been a long day

**Comment by Hoverbear** [comment]
@ccleve thanks a lot, really appreciate that comment. :) I'm gonna close this.

**Comment by ccleve** [comment]
I think this bug is back. It occurs only when I run in test mode.
```

cargo test test_skips
   Compiling relevantdb v0.1.0 (/Users/ccleve/dev/pg/RelevantDB)
    Finished test [unoptimized + debuginfo] target(s) in 13.30s
     Running unittests src/lib.rs (target/debug/deps/relevantdb-a85d2aa0af0f0030)
dyld[32760]: symbol not found in flat namespace '_UnlockReleaseBuffer'

```
UnlockReleaseBuffer is only referenced in one place in my C code. When I comment it out, the problem goes away.

I do not get the error when running in non-test mode.

Note that this is `cargo test`, not `cargo pgx test`.

It happens with 0.7.0 and 0.7.1. I did not test to see if occurs with an earlier version, but I will if that would be helpful.
