### ISSUE TITLE
default search_path='public' causes performance degradation for some functions

### ISSUE THREAD

**Issue by a-mckinley** [zombodb/pgx#58]
After doing some profiling of a tuned pgx function running in a large table scan, I noticed a lot of overhead introduced by the postgres function ```AtEOXact_GUC```.

Looking at the function comments for ```AtEOXact_GUC```, it is called when a function sets a GUC parameter via proconfig in pg_proc.  Setting proconfig to null in pg_proc for this function resulting in an 3x performance improvement in the full query.

This is really a postgres issue, but I think it would help to have a null proconfig where possible for pgx functions.

**Comment by eeeebbbbrrrr** [comment]
> I think it would help to have a null proconfig where possible for pgx functions.

me too.  The hard part is knowing when it's necessary to set the search_path.  I think the correct solution is to invent another macro that can go along with #[pg_extern]/#[pg_operator] to set the search_path to whatever you might want.

I'll get to this soon as I bet it's a thing with @zombodb too.

**Comment by eeeebbbbrrrr** [comment]
FYI:  doc updates here:  https://github.com/zombodb/pgx/commit/5081eb82e1104b41c977ae56d3fde22558fb607e

**Comment by eeeebbbbrrrr** [comment]
Meant to close this a few days ago.  It's released as of v0.1.5
