### ISSUE TITLE
Error message when installing without a ./sql folder

### ISSUE THREAD

**Issue by thebf** [zombodb/pgx#68]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.1.6/src/commands/schema.rs:217:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Solved by:
mkdir ./sql && cargo pgx schema

**Comment by eeeebbbbrrrr** [comment]
<img width="1342" alt="Screen Shot 2020-12-18 at 3 36 38 PM" src="https://user-images.githubusercontent.com/5117238/102667544-da3ed880-4146-11eb-9b2d-a15d53646614.png">

Thanks.  I think this is much better!

As an aside, you should keep the `./sql/load-order.txt` file under version control.  the `./sql/*.generated.sql` files can go into `.gitignore` (which `cargo pgx new` does by default)

**Comment by eeeebbbbrrrr** [comment]
released in 0.1.7
