### ISSUE TITLE
pgx init fails on OSX

### ISSUE THREAD

**Issue by eaubin** [zombodb/pgx#77]
I was having some trouble running `cargo pgx init --pg13 download` on my machine.  The `command.spawn()` in `configure_postgres` was failing saying `[error] No such file or directory (os error 2)`. 

The `pgdir` and `command_str` both looked fine and, PG builds from the command line.  Spawn succeeds when the command is modified to use the full path. I think this is the same behavior at https://github.com/rust-lang/rust/issues/37868#issuecomment-544601398

**Comment by eeeebbbbrrrr** [comment]
Are you on Linux or MacOS?

I'll do some investigating here.  pgx's CI system used to, until this past week actually, download all 4 versions via `cargo pgx init` and was working fine.  I rejiggered the workflow actions a bit just to improve build times, but didn't touch cargo-pgx itself.

Any other details you might can provide?

**Comment by eaubin** [comment]
This is using OSX Catalina 10.15.6, pgx 0.1.15.  The pgdir path didn't have anything strange in it (no spaces or special characters).  Stepping through it in the vs code debugger didn't work very well, I could step through pgx, but not through spawn(). I tried to grab the syscall too, but dtruss/dtrace don't seem to work anymore. Let me know if I can provide more info.

**Comment by eeeebbbbrrrr** [comment]
I'll give it a go here in a minute and report back.  My laptop is 10.15.1, so we're pretty close there...

**Comment by eeeebbbbrrrr** [comment]
yup.  It bombs here too:

```
PGX_HOME=/Users/e_ridge/pgx-issue-77 cargo pgx init --pg13 download
 Downloading Postgres v13.0 from https://ftp.postgresql.org/pub/source/v13.0/postgresql-13.0.tar.bz2
   Untarring Postgres v13.0 to /Users/e_ridge/pgx-issue-77/13.0
 Configuring Postgres v13.0
     [error] No such file or directory (os error 2)
```

awesome.

Of course, it works on my Ubuntu box just fine.

I'll sort this out today and publish a new release.  Thanks for the report.

**Comment by eeeebbbbrrrr** [comment]
okay, https://github.com/zombodb/pgx/commit/ee72f7448a3795ec8cab58c500614691f79aaba1 fixes it.

I'll work on adding MacOS to pgx' GitHub Actions workflows, but I'm going to save that for a day where I feel like being incredibly angry and frustrated.

I'll have a v0.1.17 out in an hour or so.

**Comment by eeeebbbbrrrr** [comment]
alrighty, v0.1.17 is released:  https://github.com/zombodb/pgx/releases/tag/v0.1.17

Thanks for the report.  This stuff is sometimes harder than it should be.  Also, how the f* did this ever work?!?11one!!!
